server {
    listen 80;
    server_name www.aasthaskincentre.in;
    return 301 https://www.aasthaskincentre.in$request_uri;
}

server {
    listen 443 ssl http2;
    server_name www.aasthaskincentre.in;

    root /var/www/aastha-static-site-starter;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
}

server {
    listen 80;
    listen 443 ssl http2;
    server_name aasthaskincentre.in aasthaskincentre.com www.aasthaskincentre.com;
    return 301 https://www.aasthaskincentre.in$request_uri;
}
