#!/usr/bin/env python3
"""Final public-fact sweep for schedule variants generated by older page templates."""
from pathlib import Path
import re

EXACT_REPLACEMENTS = {
    "Mon–Sat 11:00 AM–4:00 PM<br>Sun 11:00 AM–3:00 PM":
        "11:00 AM–3:00 PM",
    "Mon–Sat 6:00 PM–8:00 PM<br>Sun 10:30 AM–12:00 PM":
        "6:00 PM–8:00 PM",
    "Mon–Sat 10:00 AM–8:00 PM<br>Sun 10:00 AM–3:00 PM":
        "10:00 AM–8:00 PM",
    "Mon–Sat 10:00 AM–8:00 PM<br>Sun 10:00 AM–2:00 PM":
        "10:00 AM–8:00 PM",
    "Monday–Saturday 11 AM–4 PM and Sunday 11 AM–3 PM.":
        "11 AM–3 PM. Please confirm same-day availability before travelling.",
    "Monday–Saturday 11 AM–4 PM and Sunday 11 AM–3 PM":
        "11 AM–3 PM. Please confirm same-day availability before travelling",
    "Monday–Saturday 6 PM–8 PM, with Sunday 10:30 AM–12 PM.":
        "6 PM–8 PM. Please confirm same-day availability before travelling.",
    "Monday–Saturday 6 PM–8 PM, with Sunday 10:30 AM–12 PM":
        "6 PM–8 PM. Please confirm same-day availability before travelling",
    "Dr. Cheena: Mon–Sat 11:00 AM–4:00 PM":
        "Dr. Cheena: 11:00 AM–3:00 PM",
    "Dr. Cheena: Mon–Sat 6:00 PM–8:00 PM":
        "Dr. Cheena: 6:00 PM–8:00 PM",
}


def patch_remaining_facts(pages: list[Path]) -> int:
    changed = 0
    for page in pages:
        normalized = page.as_posix().replace("\\", "/")
        if "/admin/" in normalized:
            continue

        source = page.read_text(encoding="utf-8")
        updated = source
        for old, new in EXACT_REPLACEMENTS.items():
            if old in updated:
                updated = updated.replace(old, new)
                changed += 1

        # Catch older template variants that split the same schedules across
        # slightly different markup. These are known stale clinic values.
        regex_replacements = (
            (r"11:00 AM–4:00 PM", "11:00 AM–3:00 PM"),
            (r"11 AM–4 PM", "11 AM–3 PM"),
            (r'<div class="v4-fact"><small>Sunday doctor</small>.*?</div>', ""),
            (r"<li>Sunday doctor hours:\s*[^<]+</li>", ""),
            (r"(?:<br>\s*)?Sun(?:day)?\s+11:00 AM–3:00 PM", ""),
            (r"(?:<br>\s*)?Sun(?:day)?\s+10:30 AM–12:00 PM", ""),
            (r"(?:<br>\s*)?Sun(?:day)?\s+11 AM–3 PM", ""),
            (r"(?:<br>\s*)?Sun(?:day)?\s+10:30 AM–12 PM", ""),
            (r'<small>Doctor</small><strong>11 AM–3 PM</strong><p>Monday–Saturday\.</p>',
             '<small>Doctor</small><strong>11 AM–3 PM</strong><p>Current consultation slot. Confirm same-day availability.</p>'),
            (r'<small>Doctor</small><strong>6 PM–8 PM</strong><p>Monday–Saturday\.</p>',
             '<small>Doctor</small><strong>6 PM–8 PM</strong><p>Current consultation slot. Confirm same-day availability.</p>'),
            (r'<small>Reception</small><strong>10 AM–8 PM</strong><p>Monday–Saturday\.</p>',
             '<small>Clinic hours</small><strong>10 AM–8 PM</strong><p>Confirm same-day availability before travelling.</p>'),
        )
        for pattern, replacement in regex_replacements:
            updated, count = re.subn(pattern, replacement, updated, flags=re.I | re.S)
            changed += count

        # Avoid stray line breaks after removing obsolete Sunday windows.
        updated = re.sub(r"(<br>\s*){2,}", "<br>", updated, flags=re.I)
        updated = re.sub(r"<br>\s*</p>", "</p>", updated, flags=re.I)

        if updated != source:
            page.write_text(updated, encoding="utf-8")

    print(f"Final stale-fact variants reconciled: {changed}")
    return changed
