#!/usr/bin/env python3
"""Generate the next premium concept migration batch for preview builds only."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]
CONCEPT = ROOT / "concept"

PAGES = [
    {
        "slug":"black-neck-acanthosis-nigricans-treatment","title":"Black Neck & Acanthosis Nigricans","kicker":"Neck pigmentation & metabolic clues · Jammu","hero":"Dark neck can be a <em>skin sign</em>, not surface dirt.",
        "copy":"Acanthosis nigricans can look darker, thicker and velvety, especially in body folds. Assessment separates it from friction, irritation, infection and other pigment conditions before treatment is chosen.","image":"pigmentation-care.svg",
        "facts":[("Pattern","Dark + velvety","Texture matters as much as colour."),("Common association","Insulin resistance","A skin sign can justify metabolic assessment without proving diabetes."),("Not contagious","No","It does not spread through touch, towels or clothing."),("Avoid","Aggressive scrubbing","Friction can worsen irritation and pigmentation.")],
        "explorer_title":"Not every dark neck has the same cause.","explorer_copy":"Explore the patterns that change the next step.",
        "tabs":[("Acanthosis","Velvety thickening","Dark, slightly raised or velvety skin in the neck, underarms or other folds can fit acanthosis nigricans.","Metabolic and hormonal context may matter."),("Friction","Repeated rubbing","Collars, repeated rubbing and scrubbing can produce irritation and post-inflammatory colour change.","Removing the source of friction may be part of treatment."),("Inflammation","After a rash","Contact dermatitis, product irritation or other inflammation can leave darker skin after the active rash settles.","Treat the inflammation before chasing the colour."),("Look-alike","Infection / other cause","Fungal, bacterial and other pigment disorders can sometimes resemble a simple ‘black neck’ complaint.","Diagnosis comes before peels or bleaching products.")],
        "assessment_title":"Colour, texture and medical context belong in the same assessment.",
        "assessment":[("Texture","Velvety thickening and increased skin lines point differently from flat pigmentation."),("Distribution","Neck, underarms, groin, knuckles and other folds can reveal a broader pattern."),("Medical context","Weight change, PCOS features, medicines and metabolic risk may be relevant."),("Testing","Blood or metabolic testing is considered when the history and examination justify it.")],
        "route_title":"Treat the cause and the skin together.","steps":[("Confirm","Name the pattern first.","Separate acanthosis nigricans from friction, dermatitis, infection and other pigmentation."),("Context","Check what may be driving it.","Medical history and metabolic or hormonal clues can change the plan."),("Skin care","Reduce irritation and excess thickening.","Gentle skin care and selected topical treatment may be used according to the diagnosis."),("Review","Track texture as well as colour.","Improvement can be gradual and recurrence depends partly on the underlying driver.")],
        "faqs":[("Is black neck caused by dirt?","Usually not. Acanthosis nigricans reflects changes within the skin and cannot simply be scrubbed away."),("Does acanthosis mean diabetes?","No. It can be associated with insulin resistance or metabolic risk, but it does not by itself prove diabetes."),("Can peels fix it?","A peel may be considered in selected cases, but treatment should address the diagnosis and any underlying driver rather than colour alone.")]
    },
    {
        "slug":"chickenpox-scar-treatment","title":"Chickenpox Scar Treatment","kicker":"Post-chickenpox scars · Jammu","hero":"Treat the <em>scar architecture</em>, not just the mark.",
        "copy":"Chickenpox can leave indented scars, sharp-edged pits, broader depressions or flat dark and pale marks. Texture and pigment need to be separated before choosing a procedure.","image":"acne-care.svg",
        "facts":[("Common type","Atrophic scars","Many scars sit below the surrounding skin."),("Colour ≠ scar","Important","A flat dark mark is not the same as a true depression."),("Mixed patterns","Common","Different scars may need different procedures."),("Goal","Improvement","Procedures can soften scars but do not erase mature scars completely.")],
        "explorer_title":"Chickenpox can leave more than one kind of mark.","explorer_copy":"The scar type changes the treatment strategy.",
        "tabs":[("Round depression","Defined edges","A circular or oval depressed scar may behave differently from a narrow deep pit.","Resurfacing or focal treatment may be considered after assessment."),("Narrow pit","Deep opening","Small deep scars can resemble ice-pick scars and may need a focal approach.","One broad resurfacing treatment may not be enough."),("Broad shallow scar","Soft edges","Wider depressions may respond to collagen remodelling or resurfacing depending on depth and skin tone.","Skin type and pigment risk affect settings."),("Flat pigment mark","Colour only","Brown, grey or pale marks may remain level with the surrounding skin.","Pigment treatment cannot lift a true indentation—and scar procedures do not automatically correct colour.")],
        "assessment_title":"The scar should be mapped before the device is chosen.",
        "assessment":[("Depth","Shallow and deep scars behave differently."),("Border","Sharp edges, rolling edges and tethering change procedure choice."),("Skin tone","Pigmentation risk affects preparation, settings and aftercare."),("History","Keloid tendency, medicines and previous procedures matter.")],
        "route_title":"Match each scar to the problem underneath it.","steps":[("Classify","Separate texture from pigment.","Confirm whether the concern is a true scar, a colour change or both."),("Map","Identify depth and tethering.","The structure of each scar determines whether focal treatment, release or resurfacing is relevant."),("Combine","Use complementary procedures when needed.","Fractional CO₂, MNRF, focal techniques or other approaches may be combined in selected cases."),("Protect","Plan healing and pigment prevention.","Sun protection and aftercare are especially important in Indian skin tones.")],
        "faqs":[("Can creams remove pitted scars?","Creams can support skin quality or pigmentation, but a mature deep depression usually needs a procedure to meaningfully change texture."),("Are chickenpox scars the same as acne scars?","They can share structural features, but the pattern is not identical and each scar still needs individual assessment."),("Can fractional CO₂ help?","It may help selected shallow-to-medium scars and texture, but suitability, downtime and pigment risk must be assessed first.")]
    },
    {
        "slug":"corn-removal-treatment","title":"Corn Removal Treatment","kicker":"Painful foot corns · Jammu","hero":"A painful hard spot needs the <em>right label</em> first.",
        "copy":"Corns form from repeated pressure and friction, but plantar warts, calluses and other lesions can look similar. Diagnosis comes before acids, cutting or freezing.","image":"medical-care.svg",
        "facts":[("Corn","Pressure lesion","Usually focused around a central keratin core."),("Wart","Viral growth","Can interrupt skin lines and may spread."),("Recurrence","Pressure matters","A corn often returns if footwear or structural pressure continues."),("High risk","Diabetes / poor circulation","Self-cutting or strong acids can be unsafe.")],
        "explorer_title":"Corn, callus and wart are not interchangeable.","explorer_copy":"Small visual clues can change the treatment completely.",
        "tabs":[("Hard corn","Focused core","A compact, painful lesion often forms over a dry pressure point such as a toe joint or the outer little toe.","Direct pressure can push the dense core inward."),("Soft corn","Between toes","Moisture can keep a corn soft and whitish between adjacent toes.","Toe-to-toe friction and footwear pressure matter."),("Callus","Broad thickening","A callus is usually wider and more diffuse than a corn.","It often reflects a larger pressure pattern rather than one central core."),("Plantar wart","Viral look-alike","A wart may look rough, interrupt normal skin lines and show tiny dark vascular dots.","Treating a wart like a corn can delay the right care.")],
        "assessment_title":"The pressure source matters as much as the lesion.",
        "assessment":[("Location","Toe tops, side of the little toe, sole and between toes suggest different pressure patterns."),("Footwear","Both tight shoes and loose sliding footwear can create repeated friction."),("Structure","Hammertoe, bunion or altered pressure distribution can drive recurrence."),("Risk","Diabetes, poor circulation or reduced sensation change what is safe to do.")],
        "route_title":"Relieve the lesion, then reduce the pressure that rebuilt it.","steps":[("Identify","Confirm corn versus wart or another lesion.","Examination comes before destructive treatment."),("Unload","Reduce pressure and friction.","Footwear, padding or pressure redistribution can be central to long-term control."),("Treat","Address the thickened lesion safely.","Appropriate debridement or other treatment depends on diagnosis and medical risk."),("Prevent","Correct the recurring mechanical trigger.","Persistent structural pressure may require podiatry or orthopaedic assessment.")],
        "faqs":[("Does a corn have a root?","No. It has a dense central keratin core, not a living root."),("Why does a corn come back?","If the original pressure or friction remains, the skin can thicken again."),("Should I cut it myself?","Self-cutting can injure skin, especially in diabetes or poor circulation. Diagnosis and safe treatment are preferable.")]
    },
    {
        "slug":"cyst-lipoma-removal","title":"Cyst & Lipoma Assessment","kicker":"Skin lumps & swellings · Jammu","hero":"Not every lump should go straight to <em>removal.</em>",
        "copy":"Cysts, lipomas, abscesses and other lumps can feel similar. The first job is to identify what the swelling is, whether it is inflamed, and whether imaging, biopsy, observation or removal is appropriate.","image":"medical-care.svg",
        "facts":[("Cyst","Sac-like lump","May contain keratin, fluid or inflammatory material."),("Lipoma","Fatty lump","Often soft, slow-growing and movable."),("Inflamed lump","Different pathway","Redness, pain or pus may mean inflammation or abscess."),("Changing lump","Assess promptly","Growth, firmness, fixation or pain may need imaging or biopsy.")],
        "explorer_title":"Lumps have different behaviour beneath the skin.","explorer_copy":"Use the pattern explorer to see why removal is not the first step for every lump.",
        "tabs":[("Epidermoid cyst","Round + possible central pore","A cyst may be firm or movable and can occasionally release thick material.","Inflammation can make a previously quiet cyst painful and red."),("Pilar cyst","Often scalp","Pilar cysts commonly occur on the scalp and can catch during combing or become inflamed.","More than one can occur."),("Lipoma","Soft + rubbery","A lipoma is usually a slow-growing fatty lump with normal skin above it.","Many do not need treatment once the diagnosis is clear."),("Red painful lump","Possible abscess","Pain, warmth, pus or rapid change may point away from routine elective removal.","Infection or inflammation may need a different first step.")],
        "assessment_title":"Size, mobility and behaviour determine the next step.",
        "assessment":[("Growth","A rapidly enlarging or changing lump deserves earlier assessment."),("Texture","Soft, firm, fluctuant and fixed lumps suggest different possibilities."),("Inflammation","Heat, redness, discharge and fever alter the treatment pathway."),("Uncertainty","Deep, unusual or fixed lesions may need imaging, biopsy or referral.")],
        "route_title":"Diagnose first. Remove only when removal is the right answer.","steps":[("Examine","Identify the likely type of lump.","History and palpation help separate cyst, lipoma, abscess and other causes."),("Investigate","Use imaging or biopsy when needed.","Not every superficial lump needs a scan, but uncertainty changes the threshold."),("Plan","Choose observation, drainage, excision or referral.","The safest option depends on diagnosis, size, site and inflammation."),("Review","Use pathology when clinically appropriate.","Tissue examination may be advised when the diagnosis needs confirmation.")],
        "faqs":[("Does every cyst need removal?","No. Small stable asymptomatic cysts may simply be observed after diagnosis."),("Does every lipoma need surgery?","No. Removal is usually considered for symptoms, growth, functional problems, cosmetic concern or diagnostic uncertainty."),("Can an inflamed cyst be removed immediately?","Sometimes active inflammation changes the timing or method. Assessment determines whether drainage, medical treatment or later excision is more appropriate.")]
    },
    {
        "slug":"molluscum-contagiosum-treatment","title":"Molluscum Contagiosum","kicker":"Viral skin bumps · children & adults · Jammu","hero":"Small bumps. <em>Contagious virus.</em> Different decisions by age and site.",
        "copy":"Molluscum contagiosum causes smooth, dome-shaped bumps with a central dimple. Many cases clear naturally, while spreading, irritated or strategically located lesions may justify treatment.","image":"medical-care.svg",
        "facts":[("Cause","Poxvirus","Molluscum is a superficial viral skin infection."),("Spread","Skin contact","Touching, scratching, shaving and shared items can spread lesions."),("Children","Common","Treatment decisions depend on age, number of lesions and eczema."),("Natural course","Often self-limited","New bumps can appear while older ones resolve.")],
        "explorer_title":"The same virus can behave differently in different people.","explorer_copy":"Age, eczema, body site and immune status influence whether observation or treatment makes sense.",
        "tabs":[("Typical bumps","Smooth + central dimple","Small pearly or skin-coloured dome-shaped bumps often contain a central depression.","Do not squeeze the core at home."),("With eczema","Molluscum dermatitis","Dry itchy inflammation around the lesions can encourage scratching and spread.","The eczema and the viral bumps may both need attention."),("Childhood","Often multiple","Children commonly develop lesions on the trunk, limbs, folds, face or neck.","Pain tolerance and natural clearing matter when choosing treatment."),("Adult genital area","Needs context","Genital or groin lesions in adults can spread through intimate skin contact.","Other genital conditions may need to be excluded.")],
        "assessment_title":"Observation can be appropriate—but not automatically.",
        "assessment":[("Number","A few lesions and widespread disease are different treatment problems."),("Site","Eyelid, face, genital area and eczema-prone skin need extra care."),("Spread","Scratching, shaving and household contact can keep seeding new lesions."),("Immunity","Extensive or persistent disease may justify evaluation for reduced immunity.")],
        "route_title":"Balance natural clearing against spread, irritation and practicality.","steps":[("Confirm","Make sure the bumps are molluscum.","Warts and other growths can resemble viral molluscum."),("Decide","Observe or treat based on context.","Age, site, lesion count, eczema and patient preference influence the choice."),("Control","Treat selected lesions and surrounding dermatitis.","The method must suit the body site and patient tolerance."),("Prevent","Reduce autoinoculation and household spread.","Avoid picking, squeezing and sharing personal items while lesions are present.")],
        "faqs":[("Is molluscum caused by poor hygiene?","No. It is a viral infection spread by direct contact and contaminated objects."),("Does every child need treatment?","No. Observation can be reasonable in selected children because the infection often clears naturally."),("Can it come back?","New lesions can appear from earlier spread or re-exposure even while treated lesions are disappearing.")]
    },
    {
        "slug":"paediatric-dermatology","title":"Paediatric Dermatology","kicker":"Dermatologist-led child skin care · Jammu","hero":"Children’s skin needs <em>age-aware</em> dermatology.",
        "copy":"From eczema and diaper rash to fungal infection, molluscum, warts, acne and scalp concerns, treatment strength and advice need to match the child’s age, body site and diagnosis.","image":"medical-care.svg",
        "facts":[("Scope","Skin · hair · nails","Dermatology concerns can affect infants, children and teenagers."),("Eczema","Common","Barrier care and age-appropriate treatment are central."),("Medicines","Not mini-adult doses","Strength, body site and duration matter more in children."),("Complex cases","Referral when needed","Rare or severe disorders may need paediatric subspecialty care.")],
        "explorer_title":"Age changes both the diagnosis and the treatment choices.","explorer_copy":"Explore common childhood dermatology pathways without treating every rash the same way.",
        "tabs":[("Eczema","Dry + itchy + recurring","Childhood atopic dermatitis often needs gentle bathing, frequent moisturising and suitable anti-inflammatory treatment.","Eczema is not contagious."),("Infections","Fungal / bacterial / viral","Ringworm, impetigo, molluscum, warts and scabies all need different management.","Steroid-combination creams without diagnosis can complicate infections."),("Diaper area","Moist + occluded","Irritant rash, yeast and other conditions can overlap beneath nappies.","Gentle cleansing, barrier protection and diagnosis matter."),("Teen skin","Acne + scalp concerns","Adolescents may need acne, dandruff, hair or pigment assessment.","Treatment should still be chosen around age and tolerability.")],
        "assessment_title":"A child’s age and body site change what is safe and useful.",
        "assessment":[("Age","Infant skin and teenage skin behave differently."),("Distribution","Face, folds, diaper area, scalp and palms/soles narrow the differential."),("Previous creams","Strong steroids, combination creams and home remedies can alter the appearance."),("Growth / nutrition","Unnecessary food restriction for eczema can create nutritional problems.")],
        "route_title":"Keep the plan simple enough for a family to actually follow.","steps":[("Identify","Name the skin problem accurately.","Similar-looking childhood rashes can have very different causes."),("Simplify","Use age-appropriate skin care.","Gentle cleansing, moisturising and barrier care often support medical treatment."),("Treat","Match medicine to age, site and severity.","Adult products should not automatically be reused on a child."),("Escalate","Refer or investigate when the pattern is unusual.","Rare, severe or treatment-resistant disease may need broader paediatric evaluation.")],
        "faqs":[("Are steroid creams always unsafe for children?","No. Appropriately selected topical corticosteroids are commonly used in childhood eczema; strength, site and duration matter."),("Should foods be removed to cure eczema?","Not routinely. Unnecessary elimination diets can create nutritional problems and should not be started simply because eczema is present."),("Can children get fungal infection and scabies?","Yes. Contagious infections are common childhood dermatology concerns and require diagnosis-specific treatment.")]
    },
    {
        "slug":"scabies-treatment","title":"Scabies Treatment","kicker":"Night itch & household spread · Jammu","hero":"Treat the patient—and the <em>contact network.</em>",
        "copy":"Scabies is caused by the human itch mite. Night-time itching, characteristic distribution and similar symptoms in close contacts can be more informative than redness alone.","image":"medical-care.svg",
        "facts":[("Cause","Human itch mite","Scabies is a parasitic infestation, not poor hygiene."),("Classic clue","Worse at night","Intense night-time itch is common."),("Spread","Close contact","Household and intimate contacts can reinfect one another."),("After treatment","Itch can persist","Residual immune itch does not always mean live mites remain.")],
        "explorer_title":"Scabies has a pattern beyond ‘itchy rash.’", "explorer_copy":"Distribution, contact history and severity help separate ordinary scabies from look-alikes and crusted disease.",
        "tabs":[("Typical adult","Finger webs + wrists","Common sites include finger webs, wrists, waist, groin, buttocks and genital skin.","The face and scalp are usually spared in healthy adults with ordinary scabies."),("Child","Wider distribution","Babies and young children can have scalp, face, palm and sole involvement.","Age changes treatment instructions."),("Nodular","Persistent itchy nodules","Groin, genital, buttock or underarm nodules can persist after treatment because inflammation may outlast the mites.","New burrows or new spreading bumps need reassessment."),("Crusted","Highly contagious","Thick crusting and widespread scale can contain very high mite numbers.","Crusted scabies needs prompt intensive medical care.")],
        "assessment_title":"Failure often comes from coordination, not just the medicine.",
        "assessment":[("Contacts","Close household and sexual contacts may need coordinated treatment."),("Timing","Symptoms can take weeks to appear after first exposure."),("Technique","Incomplete application or washing treatment off early can cause failure."),("Environment","Recently used clothing, bedding and towels need appropriate handling.")],
        "route_title":"Break the transmission loop in one coordinated plan.","steps":[("Confirm","Check the distribution and contact history.","Scabies can resemble eczema, allergy or fungal disease."),("Treat","Use a suitable scabies-killing medicine correctly.","Choice and instructions depend on age, pregnancy, medical context and severity."),("Coordinate","Treat relevant close contacts together.","Staggered household treatment can allow reinfection."),("Review","Separate post-scabetic itch from active infestation.","Persistent itch may continue after successful treatment, but new lesions need reassessment.")],
        "faqs":[("Is scabies caused by poor hygiene?","No. It can affect anyone and spreads mainly through prolonged close contact."),("Can I spread scabies before I itch?","Yes. During a first infestation, symptoms may take several weeks to appear while transmission is still possible."),("Why is everyone in the house being treated?","Untreated close contacts can pass mites back and forth even if they are not yet itchy.")]
    },
    {
        "slug":"skin-biopsy","title":"Skin Biopsy","kicker":"Diagnostic dermatology procedure · Jammu","hero":"Sometimes the safest next step is a <em>small sample.</em>",
        "copy":"A skin biopsy removes a small piece of tissue for microscopic examination. It can help clarify a changing growth, suspicious mole, persistent rash, scalp disorder or another diagnosis that remains uncertain after examination.","image":"medical-care.svg",
        "facts":[("Purpose","Diagnosis","Biopsy can confirm inflammatory, infectious and tumour-related conditions."),("Anaesthesia","Local","The biopsy site is usually numbed before tissue is taken."),("Technique","Varies","Shave, punch, curette, snip or excisional approaches sample different depths."),("Result","Histopathology","The tissue is examined by a laboratory rather than instantly in the clinic.")],
        "explorer_title":"Different questions need different biopsy depths.","explorer_copy":"The technique is chosen around the suspected diagnosis, not convenience alone.",
        "tabs":[("Shave","Superficial sample","A shave removes a thin portion of a raised or superficial lesion.","It does not sample the same depth as a punch or excision."),("Punch","Cylinder of skin","A circular punch can capture several skin layers and is useful for selected inflammatory or scalp conditions.","Stitches may be needed depending on size and site."),("Excisional","Whole lesion","An excisional biopsy removes the visible lesion when that approach fits the diagnostic question.","Margins and technique depend on the clinical purpose."),("Rash biopsy","Choose the right site","Persistent or atypical rashes sometimes need tissue from a carefully selected active area.","A poorly chosen site may not show the features needed for diagnosis.")],
        "assessment_title":"The biopsy starts with choosing the right lesion and the right part of it.",
        "assessment":[("Change","Growth, bleeding, colour change or non-healing behaviour can raise the need for tissue diagnosis."),("Rash pattern","Persistent, blistering, ulcerating or treatment-resistant rashes may justify biopsy."),("Medicines","Blood-thinning medicines, allergies and healing history affect planning."),("Site","Face, scalp, nail and other areas need technique-specific planning.")],
        "route_title":"Ask a precise question, take the right sample, then act on the result.","steps":[("Select","Choose the best site to sample.","The clinical question determines which lesion and which part of the lesion is most useful."),("Sample","Use the appropriate technique.","Local anaesthetic is used and the required depth is removed."),("Lab","Send tissue for histopathology.","Microscopic examination can confirm or narrow the diagnosis."),("Plan","Use the report with the clinical picture.","Follow-up may involve treatment, monitoring, complete removal or referral.")],
        "faqs":[("Does needing a biopsy mean cancer?","No. Biopsies are also used for inflammatory, infectious and other uncertain skin conditions."),("Will a biopsy leave a scar?","Any procedure that cuts the skin can leave a scar. Size, site, technique and individual healing all influence its appearance."),("How quickly is the result available?","Timing depends on the pathology laboratory and whether special stains or additional analysis are needed.")]
    },
    {
        "slug":"skin-cancer-screening","title":"Skin Cancer Screening","kicker":"Moles, growths & non-healing lesions · Jammu","hero":"A changing spot deserves <em>assessment before destruction.</em>",
        "copy":"Skin cancer can occur on every skin tone. A changing mole, non-healing sore, bleeding growth, persistent rough patch or unusual nail pigment may need closer examination and, in selected cases, biopsy.","image":"medical-care.svg",
        "facts":[("Screening","Clinical examination","Moles and suspicious areas are reviewed in context."),("Warning sign","Evolution","Change over time matters."),("All skin tones","Yes","Cancer can occur on palms, soles, nails, scars and less sun-exposed sites."),("Biopsy","When uncertain","Microscopic examination may be needed to establish a diagnosis.")],
        "explorer_title":"The warning signs are broader than one ‘bad mole.’", "explorer_copy":"Use the explorer to understand which changes deserve medical review.",
        "tabs":[("ABCDE","Pigmented mole clues","Asymmetry, irregular borders, several colours, increasing diameter and evolution can raise concern.","Evolution or change is especially important."),("Non-healing sore","Persistent breakdown","A sore that repeatedly crusts, bleeds or fails to heal should be assessed.","Do not repeatedly cauterise an unexplained lesion."),("Rough / bleeding growth","Surface change","Persistent rough, scaly, bleeding or rapidly growing lesions can need examination.","Benign lesions can look similar, so diagnosis matters."),("Nail / hidden sites","Not only sun-exposed skin","Suspicious pigment under a nail, on palms, soles, scars or mucosal sites can also require assessment.","Dark skin does not eliminate skin-cancer risk.")],
        "assessment_title":"Screening is risk-based, not a guarantee that future cancer cannot occur.",
        "assessment":[("Personal history","Previous skin cancer raises future risk."),("Mole pattern","Atypical or changing moles may need closer follow-up."),("Immune status","Immunosuppression can increase risk."),("Biopsy threshold","A lesion that cannot be confidently classified may need tissue diagnosis.")],
        "route_title":"Examine first. Biopsy when needed. Treat from a diagnosis.","steps":[("Review","Identify the lesion that is changing or unusual.","History and comparison with other lesions provide context."),("Examine","Assess morphology and risk features.","Clinical examination guides whether monitoring is reasonable or more testing is needed."),("Biopsy","Sample suspicious or uncertain lesions.","A suspicious mole should not simply be destroyed before diagnostic planning."),("Refer / treat","Act on the confirmed diagnosis.","Further excision, monitoring or specialist referral depends on the pathology result.")],
        "faqs":[("Can people with dark skin develop skin cancer?","Yes. Skin cancer can affect every skin tone and can occur on palms, soles, nails and other less sun-exposed areas."),("Does every suspicious mole need biopsy?","No. Many lesions can be recognised clinically as benign, but biopsy is used when uncertainty remains or cancer needs to be excluded."),("Can a suspicious mole just be lasered off?","A suspicious lesion should be assessed properly before destructive treatment because tissue diagnosis may be important.")]
    },
    {
        "slug":"sti-std-treatment","title":"STI & Genital Skin Assessment","kicker":"Confidential sexual-health dermatology · Jammu","hero":"Genital symptoms need <em>diagnosis without judgement.</em>",
        "copy":"Discharge, ulcers, blisters, warts, itching and genital rashes can result from sexually transmitted infections or from non-STI conditions. Assessment is discreet and testing is selected around symptoms, exposure and timing.","image":"medical-care.svg",
        "facts":[("Symptoms","May be absent","Several STIs can be present without obvious symptoms."),("Genital rash","Not always STI","Fungal infection, dermatitis, psoriasis and shaving irritation can mimic infection."),("Testing","Risk-based","There is no single universal ‘complete panel’ for everyone."),("Urgent exposure","HIV PEP","Possible significant exposure needs urgent assessment because PEP must start within 72 hours.")],
        "explorer_title":"Symptoms overlap, so testing should follow the exposure story.","explorer_copy":"Different presentations point toward different examinations and tests.",
        "tabs":[("Discharge / burning","Urethral or genital symptoms","Discharge and painful urination can occur with several infections and need appropriate testing.","Empirical self-medication can obscure results."),("Ulcer / blister","Painful or painless lesions","Herpes, syphilis and non-STI causes can produce genital sores.","Timing, appearance and laboratory testing matter."),("Warts","HPV pattern","Genital warts are commonly associated with HPV, but other growths can resemble them.","Examination comes before destructive treatment."),("Itch / rash","Many look-alikes","Fungal infection, scabies, eczema, contact allergy and psoriasis may affect genital skin.","A rash alone does not prove an STI.")],
        "assessment_title":"Exposure site, timing and symptoms determine the testing plan.",
        "assessment":[("Symptoms","Absence of symptoms does not exclude infection."),("Exposure","Oral, genital and anal exposure can require different sampling sites."),("Timing","Window periods affect when tests become reliable."),("Partner care","Some confirmed infections require partner notification, testing or treatment.")],
        "route_title":"Keep the consultation confidential, specific and action-oriented.","steps":[("History","Understand symptoms and exposure without judgement.","Timing, protection used, anatomical exposure and previous testing guide the next step."),("Examine","Differentiate STI from genital dermatology look-alikes.","A focused examination can prevent unnecessary antibiotics or destructive procedures."),("Test","Choose targeted laboratory tests.","Testing depends on exposure, symptoms, pregnancy and individual risk rather than a fixed package."),("Treat / prevent","Manage the confirmed condition and reduce reinfection.","Treatment, partner care, vaccination and safer-sex advice are tailored to the diagnosis.")],
        "warning":"Possible significant HIV exposure within the last 72 hours needs urgent medical assessment for PEP; do not wait for a routine clinic reply.",
        "faqs":[("Can I have an STI without symptoms?","Yes. Several infections can remain symptom-free, which is why testing may be recommended after an exposure."),("Is every genital rash an STI?","No. Fungal infection, eczema, psoriasis, scabies and irritation can mimic an STI."),("Is the consultation confidential?","Sexual-health consultations are handled discreetly and respectfully, subject to applicable medical-record, public-health, safeguarding and legal requirements.")]
    },
    {
        "slug":"white-hair-removal","title":"White & Grey Hair Removal","kicker":"Light-coloured unwanted hair · Jammu","hero":"White hair changes the <em>technology question.</em>",
        "copy":"Conventional laser hair reduction depends on pigment in the hair shaft. Fully white hair contains too little melanin for reliable laser targeting, so assessment may lead to a different method such as electrolysis or temporary mechanical removal.","image":"hair-care.svg",
        "facts":[("Dark hair","Laser target","Melanin allows suitable dark hairs to absorb laser energy."),("White hair","Low pigment","Fully white hairs generally do not respond to conventional pigment-dependent hair lasers."),("Alternative","Electrolysis","Treats individual follicles without relying on hair colour."),("Availability","Confirm after assessment","Electrolysis location and availability should be confirmed rather than assumed.")],
        "explorer_title":"Hair colour determines which technology can actually see the follicle.","explorer_copy":"Mixed dark and white hair often needs a mixed strategy.",
        "tabs":[("Dark coarse hair","Laser-responsive pattern","Suitable pigmented hairs may respond to laser hair reduction depending on skin type and body site.","Reduction still requires multiple sessions because hair grows in cycles."),("Grey hair","Variable pigment","Partially grey hairs may contain inconsistent pigment and can respond unpredictably to laser.","Assessment matters more than the label ‘grey’."),("White hair","No useful melanin target","Conventional laser cannot reliably target a fully white shaft.","Electrolysis is the established direct-removal method for individual white hairs."),("Mixed area","Two technologies","Dark and white hairs in the same area may need laser for pigmented hairs and another method for residual white hairs.","Do not expect one device to treat both equally.")],
        "assessment_title":"Count, colour, thickness and hormonal context shape the plan.",
        "assessment":[("Colour","White, grey and dark hairs respond differently to light-based devices."),("Density","A few isolated hairs and a dense field have different time requirements."),("Site","Chin, upper lip, neck and body areas have different growth patterns and sensitivity."),("Hormonal clues","New coarse facial hair may justify assessment for hormonal drivers.")],
        "route_title":"Use pigment-dependent technology only where pigment exists.","steps":[("Classify","Separate dark, grey and white hairs.","The proportion of pigmented hair determines how much laser can contribute."),("Assess","Review skin type, site and hormonal pattern.","Underlying hair growth can continue even after individual follicles are treated."),("Choose","Match laser, electrolysis or temporary removal to the hair.","Electrolysis availability and treatment location are confirmed after assessment."),("Repeat","Work with the hair-growth cycle.","Multiple visits are expected because not every follicle is treatable at the same time.")],
        "faqs":[("Can laser remove completely white hair?","Conventional laser hair reduction generally cannot because fully white hair lacks enough melanin to absorb the laser energy."),("What method can treat white hair?","Electrolysis can treat individual follicles without relying on hair pigment; suitability and availability are confirmed after assessment."),("Does shaving make white hair thicker?","No. Shaving cuts the shaft at the surface and does not increase the number or biological thickness of follicles.")]
    },
    {
        "slug":"xanthelasma-removal","title":"Xanthelasma Assessment & Removal","kicker":"Yellow eyelid plaques · Jammu","hero":"Eyelid plaques need <em>metabolic context</em> and careful anatomy.",
        "copy":"Xanthelasma is a benign yellow or yellow-orange plaque around the eyelids. Removal can be considered for appearance, but the plan also includes checking whether lipid or metabolic risk needs attention.","image":"pigmentation-care.svg",
        "facts":[("Condition","Benign eyelid plaque","Xanthelasma contains lipid-filled cells in superficial skin."),("Cholesterol","May be normal or high","A lipid profile is commonly considered even when the plaque is cosmetic."),("Treatment","Method varies","Chemical, laser, electrosurgical or surgical options depend on size and depth."),("Recurrence","Possible","No removal method guarantees that xanthelasma will never return.")],
        "explorer_title":"Size and depth matter more than choosing a fashionable device.","explorer_copy":"The eyelid is thin, mobile skin; treatment has to respect anatomy and recurrence risk.",
        "tabs":[("Small superficial","Limited plaque","A small shallow plaque may be suitable for a less invasive approach depending on exact location.","Depth can be difficult to judge without examination."),("Larger plaque","More surface area","Larger lesions may require a different technique or staged treatment.","Healing and pigment change become more relevant."),("Deep / recurrent","Higher recurrence concern","Previously treated or deeper plaques may be more difficult to clear completely.","Treatment choice must account for scarring and eyelid distortion risk."),("Uncertain lesion","Confirm diagnosis","Not every yellow or eyelid growth is xanthelasma.","Biopsy or specialist assessment may be needed when the appearance is atypical.")],
        "assessment_title":"Treat the eyelid lesion and check the wider metabolic picture.",
        "assessment":[("Anatomy","Upper/lower lid and distance from the lid margin affect technique."),("Depth","Superficial and deeper plaques behave differently."),("Lipid risk","Cholesterol, triglycerides, diabetes and cardiovascular risk may be reviewed."),("Previous treatment","Recurrence and scarring history influence the next approach.")],
        "route_title":"Confirm, assess depth, choose the method, then watch for recurrence.","steps":[("Confirm","Make sure the plaque is xanthelasma.","Atypical eyelid lesions may need another diagnostic pathway."),("Check","Review metabolic risk where appropriate.","A lipid profile can be relevant even though xanthelasma may occur with normal results."),("Treat","Select the removal technique around eyelid anatomy.","Chemical, CO₂ laser, electrosurgical/radiofrequency or surgical options may be considered."),("Review","Monitor healing and recurrence.","Established plaques may recur after any method and metabolic control does not automatically erase existing lesions.")],
        "faqs":[("Does xanthelasma always mean high cholesterol?","No. Some patients have normal routine lipid results, but lipid assessment is commonly recommended."),("Can lowering cholesterol make the plaque disappear?","Established plaques often remain and may still need a separate cosmetic procedure."),("Can xanthelasma return after removal?","Yes. Recurrence can occur after any technique, especially with deep or extensive disease.")]
    },
]


def render(page):
    slug = page["slug"]
    facts = "".join(f'<div class="v4-fact"><small>{escape(a)}</small><strong>{escape(b)}</strong><p>{escape(c)}</p></div>' for a,b,c in page["facts"])
    tabs = "".join(
        f'<button data-v8-topic aria-selected="{"true" if i == 0 else "false"}" data-title="{escape(title, quote=True)}" data-copy="{escape(copy, quote=True)}" data-note="{escape(note, quote=True)}"><small>{i+1:02d}</small><strong>{escape(label)}</strong></button>'
        for i,(label,title,copy,note) in enumerate(page["tabs"])
    )
    first = page["tabs"][0]
    assessment = "".join(f'<div class="fact-row"><dt>{escape(k)}</dt><dd>{escape(v)}</dd></div>' for k,v in page["assessment"])
    nav = "".join(f'<button class="{"is-active" if i == 0 else ""}" data-process-target="{slug}-step-{i+1}">{i+1:02d} {escape(verb)}</button>' for i,(verb,_,_) in enumerate(page["steps"]))
    chapters = "".join(f'<article class="process-chapter" id="{slug}-step-{i+1}" data-process-chapter><span class="kicker">{i+1:02d} / {escape(verb)}</span><h3>{escape(title)}</h3><p>{escape(copy)}</p></article>' for i,(verb,title,copy) in enumerate(page["steps"]))
    faqs = "".join(f'<details><summary>{escape(q)}</summary><div class="answer"><p>{escape(a)}</p></div></details>' for q,a in page["faqs"])
    warning = ""
    if page.get("warning"):
        warning = f'<div class="v5-warning"><span>!</span><div><strong>{escape(page["warning"])}</strong><p>Seek time-sensitive medical care rather than waiting for a routine website or WhatsApp reply.</p></div></div>'
    return f'''<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{escape(page["title"])} in Jammu — Aastha Concept</title><link rel="stylesheet" href="/assets/css/editorial-concept-v1.css"><link rel="stylesheet" href="/assets/css/editorial-concept-v2.css"></head><body class="concept-page treatment-page"><header class="concept-nav"><div class="concept-shell"><a class="brand-mark" href="/concept/">AASTHA <span>Skin Centre · Jammu</span></a><nav class="concept-links"><a href="/concept/conditions/">Concerns</a><a href="#patterns">Explore</a><a href="#assessment">Assessment</a><a href="#route">Pathway</a></nav><a class="nav-cta" href="/concept/book-appointment/">Book consultation</a></div></header><main>
<section class="editorial-hero"><div class="concept-shell hero-grid"><div><span class="kicker">{escape(page["kicker"])}</span><h1 class="hero-title">{page["hero"]}</h1><p class="hero-copy">{escape(page["copy"])}</p><div class="hero-actions"><a class="btn" href="#patterns">Explore this guide ↓</a><a class="btn alt" href="/concept/book-appointment/">Book assessment</a></div></div><figure class="hero-art"><img src="/assets/images/professional/{escape(page["image"])}" alt="Dermatology guide illustration"><figcaption class="art-label">{escape(page["title"])}</figcaption></figure></div></section>
<section class="editorial-section"><div class="concept-shell"><div class="v4-facts">{facts}</div></div></section>
<section class="editorial-section" id="patterns"><div class="concept-shell"><div class="section-head"><div><span class="section-no">01 / Explore</span></div><div><h2 class="display-heading">{escape(page["explorer_title"])}</h2><p class="section-copy">{escape(page["explorer_copy"])}</p></div></div><div class="v8-topic-explorer" data-v8-explorer><div class="v8-topic-tabs">{tabs}</div><div class="v8-topic-stage"><span>Selected pattern</span><h3 data-v8-title>{escape(first[1])}</h3><p data-v8-copy>{escape(first[2])}</p><span data-v8-note>{escape(first[3])}</span></div></div></div></section>
<section class="editorial-section" id="assessment"><div class="concept-shell"><div class="section-head"><div><span class="section-no">02 / Assessment</span></div><div><h2 class="display-heading">{escape(page["assessment_title"])}</h2></div></div><dl class="fact-table">{assessment}</dl></div></section>
<section class="editorial-section" id="route"><div class="concept-shell"><div class="section-head"><div><span class="section-no">03 / Care pathway</span></div><div><h2 class="display-heading">{escape(page["route_title"])}</h2></div></div><div class="process-stage"><div class="process-nav">{nav}</div><div class="process-content">{chapters}</div></div></div></section>
<section class="editorial-section" id="faq"><div class="concept-shell"><div class="section-head"><div><span class="section-no">04 / Questions</span></div><div><h2 class="display-heading">Practical questions, answered clearly.</h2></div></div><div class="v3-accordion">{faqs}</div>{warning}<div class="hero-actions"><a class="btn" href="/concept/book-appointment/">Book consultation</a><a class="btn alt" href="/concept/treatments/">All treatments</a></div></div></section>
</main><footer class="concept-footer"><div class="concept-shell"><p class="footer-word">{escape(page["title"].split()[0].upper())}.</p></div></footer><script src="/assets/js/editorial-concept-v1.js" defer></script><script src="/assets/js/editorial-concept-v2.js" defer></script></body></html>'''


def main():
    for page in PAGES:
        target = CONCEPT / page["slug"] / "index.html"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render(page), encoding="utf-8")
    print(f"Generated {len(PAGES)} v13 concept pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
